# Generated by Django 3.0.2 on 2020-01-11 17:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('channel', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='channel',
            name='date',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
