# Generated by Django 3.0.2 on 2020-01-30 16:29

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('channel', '0004_channel_authors'),
    ]

    operations = [
        migrations.AlterField(
            model_name='channel',
            name='authors',
            field=models.ManyToManyField(blank=True, related_name='authors', to=settings.AUTH_USER_MODEL),
        ),
    ]
