# Generated by Django 3.0.2 on 2020-01-30 16:34

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('user', '0011_auto_20200130_1959'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='connection',
            name='follower',
        ),
        migrations.AddField(
            model_name='connection',
            name='creator',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='connection_create_set', to=settings.AUTH_USER_MODEL),
        ),
    ]
