# Generated by Django 3.0.2 on 2020-01-30 10:01

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('post', '0003_auto_20200111_2110'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='reply_to',
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to='post.Comment'),
        ),
        migrations.DeleteModel(name='DisLike', ),
        migrations.DeleteModel(name='Like', ),
    ]
