# Generated by Django 3.0.2 on 2020-02-02 18:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notification', '0002_auto_20200202_2034'),
    ]

    operations = [
        migrations.AddField(
            model_name='notification',
            name='target_post',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AlterField(
            model_name='notification',
            name='kind',
            field=models.CharField(choices=[('post', 'like your post'), ('comment', 'a new comment added to '), ('follow', 'follow you')], max_length=50),
        ),
    ]
